-- ============================================
-- Enhanced Billing Integration for Laboratory Dashboard
-- ============================================
-- This script adds additional safeguards and optimizations
-- to the existing auto-invoice system
--
-- IMPORTANT: This is an enhancement to 004_laboratory_dashboard.sql
-- Make sure that script has been run first!

-- 1. Add unique constraint to prevent race conditions
-- ============================================
-- This ensures 1:1 relationship between orders and invoices at database level
DO $$
BEGIN
    -- Only add if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'lab_orders_invoice_id_unique'
    ) THEN
        ALTER TABLE lab_orders
        ADD CONSTRAINT lab_orders_invoice_id_unique UNIQUE (invoice_id);
    END IF;
END $$;

-- 2. Add index for better performance on billing queries
-- ============================================
CREATE INDEX IF NOT EXISTS idx_invoices_order_id
ON invoices(order_id);

CREATE INDEX IF NOT EXISTS idx_lab_orders_invoice_id
ON lab_orders(invoice_id);

-- 3. Add trigger to handle order cancellation → invoice cancellation
-- ============================================
CREATE OR REPLACE FUNCTION handle_order_cancellation()
RETURNS TRIGGER AS $$
BEGIN
  -- If order is cancelled and it had an invoice, cancel the invoice too
  IF NEW.status = 'cancelled'
     AND OLD.status != 'cancelled'
     AND NEW.invoice_id IS NOT NULL THEN

    UPDATE invoices
    SET status = 'cancelled',
        updated_at = NOW(),
        notes = COALESCE(notes || ' | ', '') || 'Cancelada por cancelación de orden'
    WHERE id = NEW.invoice_id;

    RAISE NOTICE 'Invoice % cancelled due to order % cancellation', NEW.invoice_id, NEW.id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop if exists and recreate
DROP TRIGGER IF EXISTS trigger_cancel_invoice ON lab_orders;

CREATE TRIGGER trigger_cancel_invoice
  AFTER UPDATE ON lab_orders
  FOR EACH ROW
  EXECUTE FUNCTION handle_order_cancellation();

-- 4. Add function to verify billing integrity
-- ============================================
CREATE OR REPLACE FUNCTION verify_billing_integrity(p_lab_org_id UUID)
RETURNS TABLE (
  issue_type TEXT,
  order_id UUID,
  order_number TEXT,
  details TEXT
) AS $$
BEGIN
  -- Check for completed orders without invoices
  RETURN QUERY
  SELECT
    'missing_invoice'::TEXT,
    lo.id,
    lo.order_number,
    'Order marked as ready but no invoice generated'::TEXT
  FROM lab_orders lo
  WHERE lo.lab_org_id = p_lab_org_id
    AND lo.status = 'ready'
    AND lo.invoice_id IS NULL;

  -- Check for duplicate invoice references (shouldn't happen with unique constraint)
  RETURN QUERY
  SELECT
    'duplicate_invoice'::TEXT,
    lo.id,
    lo.order_number,
    'Multiple orders pointing to same invoice: ' || lo.invoice_id::TEXT
  FROM lab_orders lo
  WHERE lo.lab_org_id = p_lab_org_id
    AND lo.invoice_id IS NOT NULL
  GROUP BY lo.invoice_id, lo.id, lo.order_number
  HAVING COUNT(*) > 1;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execution to authenticated users
GRANT EXECUTE ON FUNCTION verify_billing_integrity TO authenticated;

-- 5. Add repair function for missing invoices
-- ============================================
CREATE OR REPLACE FUNCTION repair_missing_invoices(p_lab_org_id UUID)
RETURNS TABLE (
  order_id UUID,
  order_number TEXT,
  invoice_id UUID,
  status TEXT
) AS $$
DECLARE
  v_order RECORD;
  v_invoice_id UUID;
  v_total DECIMAL(10,2);
  v_invoice_number TEXT;
BEGIN
  -- Find all ready orders without invoices
  FOR v_order IN
    SELECT lo.*
    FROM lab_orders lo
    WHERE lo.lab_org_id = p_lab_org_id
      AND lo.status = 'ready'
      AND lo.invoice_id IS NULL
  LOOP
    -- Calculate total from order items
    SELECT COALESCE(SUM(unit_price * quantity), 0)
    INTO v_total
    FROM lab_order_items
    WHERE order_id = v_order.id;

    IF v_total = 0 THEN
      v_total := 500.00; -- Default fallback
    END IF;

    -- Generate invoice number
    v_invoice_number := 'INV-' || LPAD(nextval('invoice_number_seq')::TEXT, 6, '0');

    -- Create invoice
    INSERT INTO invoices (
      invoice_number, lab_org_id, dentist_org_id, order_id,
      status, subtotal, tax_rate, tax_amount, total,
      due_date, notes, created_at, updated_at
    ) VALUES (
      v_invoice_number, v_order.lab_org_id, v_order.dentist_org_id, v_order.id,
      'pending', v_total, 0, 0, v_total,
      CURRENT_DATE + INTERVAL '30 days',
      'Auto-generated by repair function for order ' || v_order.order_number,
      NOW(), NOW()
    )
    RETURNING id INTO v_invoice_id;

    -- Update order with invoice reference
    UPDATE lab_orders
    SET invoice_id = v_invoice_id,
        updated_at = NOW()
    WHERE id = v_order.id;

    -- Return result
    RETURN QUERY
    SELECT
      v_order.id,
      v_order.order_number,
      v_invoice_id,
      'repaired'::TEXT;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execution to authenticated users
GRANT EXECUTE ON FUNCTION repair_missing_invoices TO authenticated;

-- 6. Add view for late delivery tracking
-- ============================================
CREATE OR REPLACE VIEW lab_late_deliveries AS
SELECT
  lo.id as order_id,
  lo.order_number,
  lo.lab_org_id,
  lo.dentist_org_id,
  lo.due_date,
  lo.updated_at as delivered_at,
  lo.status,
  DATE_PART('day', lo.updated_at - lo.due_date) as days_late,
  d.name as dentist_org_name
FROM lab_orders lo
JOIN organizations d ON d.id = lo.dentist_org_id
WHERE lo.status = 'delivered'
  AND lo.updated_at > lo.due_date;

GRANT SELECT ON lab_late_deliveries TO authenticated;

-- 7. Add composite index for dashboard performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_lab_orders_composite
ON lab_orders(lab_org_id, status, created_at DESC)
WHERE status NOT IN ('cancelled', 'draft');

-- 8. Add monitoring view for billing health
-- ============================================
CREATE OR REPLACE VIEW lab_billing_health AS
SELECT
  lo.lab_org_id,
  COUNT(*) FILTER (WHERE lo.status = 'ready' AND lo.invoice_id IS NULL) as missing_invoices,
  COUNT(*) FILTER (WHERE lo.status = 'ready' AND lo.invoice_id IS NOT NULL) as invoiced_orders,
  COUNT(*) FILTER (WHERE lo.status = 'delivered' AND i.status = 'pending') as unpaid_delivered,
  COUNT(*) FILTER (WHERE lo.status = 'delivered' AND i.status = 'paid') as paid_delivered,
  COALESCE(SUM(i.total) FILTER (WHERE i.status = 'paid'), 0) as total_revenue,
  COALESCE(SUM(i.total) FILTER (WHERE i.status = 'pending'), 0) as pending_revenue
FROM lab_orders lo
LEFT JOIN invoices i ON i.id = lo.invoice_id
WHERE lo.created_at >= CURRENT_DATE - INTERVAL '90 days'
GROUP BY lo.lab_org_id;

GRANT SELECT ON lab_billing_health TO authenticated;

-- ============================================
-- USAGE INSTRUCTIONS
-- ============================================
--
-- Check billing integrity:
-- SELECT * FROM verify_billing_integrity('<your-lab-org-id>');
--
-- Repair missing invoices:
-- SELECT * FROM repair_missing_invoices('<your-lab-org-id>');
--
-- View late deliveries:
-- SELECT * FROM lab_late_deliveries WHERE lab_org_id = '<your-lab-org-id>';
--
-- Monitor billing health:
-- SELECT * FROM lab_billing_health WHERE lab_org_id = '<your-lab-org-id>';
--
-- ============================================
-- TESTING
-- ============================================
--
-- Test the auto-invoice trigger:
-- 1. Create a test order
-- 2. Update status to 'ready'
-- 3. Check that invoice_id is set and invoice exists
--
-- Test the cancellation trigger:
-- 1. Create order and mark as ready (generates invoice)
-- 2. Cancel the order
-- 3. Check that invoice status is also 'cancelled'
